### ISSUE TITLE
Handle scenarios when `attempt` is > `--retries` +1

### ISSUE THREAD

**Issue by pmb59** [ebi-gene-expression-group/bulk-recalculations#52]
To avoid possible errors here:
```
def get_mem_mb(wildcards, attempt):
    """
    To adjust resources in the rules 
    attemps = reiterations + 1
    Max number attemps = 8
    """
    mem_avail = [ 2, 2, 4, 8, 16, 64, 128, 256 ]  
    return mem_avail[attempt-1] * 1000

```

**Comment by anilthanki** [comment]
Possible solutions

1. When `attempt` reach the length of `mem_avail` then stop workflow with informative message

 ```
if attmpt >= len(max_avail):
   # stop workflow with informative message
```

2. Drop the `mem_avail` and dynamically assign memory **(This can lead to job with enormous memory)**

 ```
return attempt * 1000
```

**Comment by pmb59** [comment]
Thanks @anilthanki one of your solutions has been implemented here https://github.com/ebi-gene-expression-group/bulk-recalculations/pull/51
